name: pyimage
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _python_abi3_support=1.0
  - alabaster=1.0.0
  - annotated-types=0.7.0
  - aom=3.6.0
  - app-model=0.4.0
  - appdirs=1.4.4
  - arrow-cpp=19.0.0
  - asttokens=3.0.0
  - attrs=25.4.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - babel=2.17.0
  - bermuda=0.1.6
  - blas=2.136
  - blas-devel=3.9.0
  - blosc=1.21.6
  - bokeh=3.8.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cachey=0.2.1
  - cairo=1.18.4
  - cellpose=4.0.4
  - certifi=2025.10.5
  - cffi=1.17.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=3.4.3
  - click=8.3.0
  - click-default-group=1.2.4
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.2.3
  - contourpy=1.3.1
  - cpython=3.12.11
  - crc32c=2.7.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2025.9.1
  - dask-core=2025.9.1
  - dask-image=2024.5.3
  - dav1d=1.2.1
  - dbus=1.16.2
  - debugpy=1.8.17
  - decorator=5.2.1
  - deprecated=1.2.18
  - distributed=2025.9.1
  - docformatter=1.7.7
  - docstring_parser=0.17.0
  - docutils=0.21.2
  - donfig=0.8.1.post1
  - eigen=3.4.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fastremap=1.17.7
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fill-voids=2.1.1
  - flexcache=0.3
  - flexparser=0.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.13.3
  - freetype-py=2.5.1
  - fribidi=1.0.10
  - fsspec=2025.9.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h2=4.3.0
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - heapdict=1.0.1
  - hpack=4.1.0
  - hsluv=5.0.4
  - humanfriendly=10.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - imagecodecs=2024.9.22
  - imageio=2.37.0
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - in-n-out=0.2.1
  - intel-openmp=2023.0.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarchive=3.8.1
  - libavif=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.15.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopengl-devel=1.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libuuid=2.41.2
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=20.1.8
  - llvmlite=0.45.1
  - lmdb=0.9.31
  - locket=1.0.0
  - lxml=6.0.2
  - lz4=4.3.3
  - lz4-c=1.9.4
  - magicgui=0.10.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mesalib=25.1.5
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - mysql=8.4.0
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - napari=0.6.5
  - napari-base=0.6.5
  - napari-console=0.1.3
  - napari-plugin-engine=0.2.0
  - napari-plugin-manager=0.1.6
  - napari-svg=0.2.1
  - narwhals=2.7.0
  - natsort=8.4.0
  - ncurses=6.5
  - nd2=0.10.3
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=3.0
  - npe2=0.7.9
  - numba=0.62.1
  - numcodecs=0.16.1
  - numexpr=2.13.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.9.0
  - ome-types=0.6.1
  - onnx=1.16.2
  - onnxruntime=1.22.0
  - openblas=0.3.30
  - opencv=4.10.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.4
  - orc=2.0.1
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - partd=1.4.2
  - partsegcore-compiled-backend=0.15.14
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pims=0.7
  - pint=0.25
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - pooch=1.8.2
  - prompt-toolkit=3.0.52
  - protobuf=4.25.3
  - psutil=7.1.0
  - psygnal=0.14.2
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=19.0.0
  - pycocotools=2.0.10
  - pyconify=0.2.1
  - pycparser=2.22
  - pydantic=2.12.0
  - pydantic-compat=0.1.2
  - pydantic-core=2.41.1
  - pydantic-extra-types=2.10.6
  - pygments=2.19.2
  - pyopengl=3.1.10
  - pyparsing=3.2.0
  - pyproject_hooks=1.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pyqtgraph=0.13.7
  - pysocks=1.7.1
  - python=3.12.7
  - python-build=1.3.0
  - python-dateutil=2.9.0post0
  - python-flatbuffers=25.9.23
  - python-gil=3.12.11
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.3.1
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qt-main=5.15.2
  - qtbase=6.9.2
  - qtconsole-base=5.7.0
  - qtdeclarative=6.9.2
  - qtpy=2.4.3
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2022.04.01
  - readline=8.3
  - referencing=0.36.2
  - requests=2.32.5
  - resource_backed_dask_array=0.1.0
  - rich=14.2.0
  - roifile=2025.5.10
  - roman-numerals-py=3.1.0
  - rpds-py=0.27.1
  - ruff=0.14.0
  - s2n=1.3.27
  - scikit-image=0.25.2
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - seaborn=0.13.2
  - segment-anything=1.0.1
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sip=6.12.0
  - six=1.17.0
  - slicerator=1.1.0
  - snappy=1.2.2
  - snowballstemmer=3.0.1
  - sortedcontainers=2.4.0
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - superqt=0.7.6
  - sympy=1.14.0
  - tbb=2021.8.0
  - tblib=3.1.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tifffile=2024.12.12
  - tk=8.6.15
  - tomli=2.3.0
  - tomli-w=1.2.0
  - toolz=1.0.0
  - toposort=1.10
  - torchvision=0.18.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.19.2
  - typer-slim=0.19.2
  - typer-slim-standard=0.19.2
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - untokenize=0.1.1
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vispy=0.15.2
  - wayland=1.24.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - wrapt=1.17.3
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xsdata=24.3.1
  - xyzservices=2025.4.0
  - xz=5.6.4
  - yaml=0.2.5
  - zarr=3.1.3
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.0.7
  - zstandard=0.25.0
  - zstd=1.5.7

